conformant = "Partial"
notes = """
Does not understand custom field specifiers.
Incorrectly rejects frozen dataclass that inherits from non-frozen.
Emits "attribute not initialized" error for dataclass field.
"""
output = """
dataclasses_transform_meta.py:43:0 Invalid inheritance [39]: Frozen dataclass `Customer1` cannot inherit from non-frozen dataclass `ModelBase`.
dataclasses_transform_meta.py:51:0 Invalid inheritance [39]: Non-frozen dataclass `Customer1Subclass` cannot inherit from frozen dataclass `Customer1`.
dataclasses_transform_meta.py:60:7 Unexpected keyword [28]: Unexpected keyword argument `other_name` to call `Customer1.__init__`.
dataclasses_transform_meta.py:63:0 Invalid assignment [41]: Cannot reassign final attribute `c1_1.id`.
dataclasses_transform_meta.py:66:7 Too many arguments [19]: Call `Customer1.__init__` expects 0 positional arguments, 2 were provided.
dataclasses_transform_meta.py:73:5 Unsupported operand [58]: `<` is not supported for operand types `Customer1` and `Customer1`.
dataclasses_transform_meta.py:83:7 Too many arguments [19]: Call `Customer2.__init__` expects 0 positional arguments, 2 were provided.
dataclasses_transform_meta.py:103:0 Invalid assignment [41]: Cannot reassign final attribute `c3_1.id`.
"""
conformance_automated = "Fail"
errors_diff = """
Line 43: Unexpected errors ['dataclasses_transform_meta.py:43:0 Invalid inheritance [39]: Frozen dataclass `Customer1` cannot inherit from non-frozen dataclass `ModelBase`.']
Line 60: Unexpected errors ['dataclasses_transform_meta.py:60:7 Unexpected keyword [28]: Unexpected keyword argument `other_name` to call `Customer1.__init__`.']
"""
