conformant = "Partial"
notes = """
Does not detect many subtyping rule violations for callables.
Does not correctly handle type alias parameterized by ParamSpec.
"""
errors_diff = """
Line 51: Expected 1 errors
Line 52: Expected 1 errors
Line 55: Expected 1 errors
Line 58: Expected 1 errors
Line 82: Expected 1 errors
Line 85: Expected 1 errors
Line 86: Expected 1 errors
Line 116: Expected 1 errors
Line 119: Expected 1 errors
Line 120: Expected 1 errors
Line 122: Expected 1 errors
Line 124: Expected 1 errors
Line 125: Expected 1 errors
Line 126: Expected 1 errors
Line 151: Expected 1 errors
Line 154: Expected 1 errors
Line 155: Expected 1 errors
Line 187: Expected 1 errors
Line 190: Expected 1 errors
Line 191: Expected 1 errors
Line 193: Expected 1 errors
Line 195: Expected 1 errors
Line 196: Expected 1 errors
Line 197: Expected 1 errors
Line 236: Expected 1 errors
Line 237: Expected 1 errors
Line 240: Expected 1 errors
Line 243: Expected 1 errors
Line 273: Expected 1 errors
Line 297: Expected 1 errors
Line 211: Unexpected errors ["callables_subtyping.py:211:40: \\x1b[1m\\x1b[31merror\\x1b[39m\\x1b[0m: in <module>: Invalid type annotation 'Callable[[P], None][P]'  [invalid-annotation]"]
Line 213: Unexpected errors ["callables_subtyping.py:213:5: \\x1b[1m\\x1b[31merror\\x1b[39m\\x1b[0m: in func7: Invalid type annotation 'TypeAliasWithP[P]'  [invalid-annotation]"]
Line 255: Unexpected errors ["callables_subtyping.py:255:40: \\x1b[1m\\x1b[31merror\\x1b[39m\\x1b[0m: in __call__: @typing.overload-decorated 'Overloaded9.__call__' object is not callable [not-callable]"]
Line 284: Unexpected errors ["callables_subtyping.py:284:44: \\x1b[1m\\x1b[31merror\\x1b[39m\\x1b[0m: in __call__: @typing.overload-decorated 'Overloaded10.__call__' object is not callable [not-callable]"]
"""
output = """
callables_subtyping.py:26:5: \u001b[1m\u001b[31merror\u001b[39m\u001b[0m: in func1: Type annotation for f6 does not match type of assignment [annotation-type-mismatch]

    f6: Callable[[float], float] = cb3  # E
    \u001b[1m\u001b[31m~~\u001b[39m\u001b[0m

callables_subtyping.py:29:5: \u001b[1m\u001b[31merror\u001b[39m\u001b[0m: in func1: Type annotation for f8 does not match type of assignment [annotation-type-mismatch]

    f8: Callable[[int], int] = cb2  # E
    \u001b[1m\u001b[31m~~\u001b[39m\u001b[0m

callables_subtyping.py:211:40: \u001b[1m\u001b[31merror\u001b[39m\u001b[0m: in <module>: Invalid type annotation 'Callable[[P], None][P]'  [invalid-annotation]

def func7(proto: ProtocolWithP[P], ta: TypeAliasWithP[P]):
                                       \u001b[1m\u001b[31m~~~~~~~~~~~~~~~~~\u001b[39m\u001b[0m

callables_subtyping.py:213:5: \u001b[1m\u001b[31merror\u001b[39m\u001b[0m: in func7: Invalid type annotation 'TypeAliasWithP[P]'  [invalid-annotation]

    f1: TypeAliasWithP[P] = proto  # OK
    \u001b[1m\u001b[31m~~\u001b[39m\u001b[0m

callables_subtyping.py:255:40: \u001b[1m\u001b[31merror\u001b[39m\u001b[0m: in __call__: @typing.overload-decorated 'Overloaded9.__call__' object is not callable [not-callable]

    def __call__(self, x: str) -> str: ...
                                       \u001b[1m\u001b[31m~~~\u001b[39m\u001b[0m

callables_subtyping.py:284:44: \u001b[1m\u001b[31merror\u001b[39m\u001b[0m: in __call__: @typing.overload-decorated 'Overloaded10.__call__' object is not callable [not-callable]

    def __call__(self, x: str) -> complex: ...
                                           \u001b[1m\u001b[31m~~~\u001b[39m\u001b[0m

"""
conformance_automated = "Fail"
